# How to reshape an array?

In [3]:
import numpy as np
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
reshaped_arr = np.reshape(arr, (2, 5))
print("\nReshaped array:")
print(reshaped_arr)



Reshaped array:
[[0 1 2 3 4]
 [5 6 7 8 9]]


### => the size of the matrix product must be equal to the element number in initial array

In [15]:
reshaped_arr = np.reshape(arr, (2, -1))
print("\nReshaped array:")
print(reshaped_arr)



Reshaped array:
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [17]:
arr=np.arange(15)
reshaped_arr = np.reshape(arr, (3, -1))
print("\nReshaped array:")
print(reshaped_arr)



Reshaped array:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


### => so if we want to determin just the numbers of ligne we put -1 for couloums be detected directly  

In [19]:
arr=np.arange(20)
reshaped_arr = arr.reshape(5, -1)
print("\nReshaped array:")
print(reshaped_arr)


Reshaped array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


### => we can also applay the reshape function on the array directly without using np.reshape and arr as a paramater

# Stack arrays a and b vertically

In [27]:
a=np.arange(10).reshape(2,-1)
b=np.repeat(1,10).reshape(2,-1)
c=np.concatenate([a,b],axis=0)
print("stack with concatenate",c)
d=np.vstack([a,b])
print("stack with vstack",d)
e=np.r_[a,b]
print("stack with _r",e)

stack with concatenate [[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
stack with vstack [[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
stack with _r [[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


# How to stack two arrays horizontally?

In [28]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

In [30]:
c=np.concatenate([a,b],axis=1)
print("stack with concatenate",c)
d=np.hstack([a,b])
print("stack with hstack",d)
e=np.c_[a,b]
print("stack with c_ ",e)

stack with concatenate [[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]
stack with hstack [[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]
stack with c_  [[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


# How to generate custom sequences in numpy without hardcoding?

In [37]:
a = np.array([1,2,3])
b=np.repeat(a,3)
c=np.concatenate([b,a,a,a],axis=0)
c

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [38]:
d=np.tile(a,3)
d

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

# How to get the common items between two python numpy arrays?

In [6]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
c=np.intersect1d(a,b)
c

array([2, 4])